name: Fetch latest assets

on:
  workflow_dispatch:
    inputs:
        force:
          description: 'Force refetch'
          required: false
          type: boolean
          default: false
  schedule:
    - cron: '0 0 * * 4'  # weekly auto-run (after update day)

jobs:
  fetch:
    name: Fetch assets
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_TOKEN }}

      - name: Setup bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install

      - name: Set flags
        id: flags
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ] && [ "${{ github.event.inputs.force }}" = "true" ]; then
            echo "flags=-f" >> "$GITHUB_OUTPUT"
          else
            echo "flags=" >> "$GITHUB_OUTPUT"
          fi
      
      - name: Run fetcher script
        run: |
          bun index.ts ${{ steps.flags.outputs.flags }}

      - name: Update repo with new assets
        run: |
          git config user.name github-actions[bot]
          git config user.email github-actions[bot]@users.noreply.github.com
          git add assets/* || true
          git commit -m "update assets" || echo "no changes"
          git push
